# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Purecolor
tagline:             
description:         
url:                 "http://clarkhtse.github.io"
paginate:            5
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Purecolor
  url:               http://clarkhtse.github.io
  email:             purecolor85@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/clarkhtse/clarkhtse.github.io
